baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '0xpages'
theme="archie"

copyright = "© davidxbors"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

canonifyURLs = true

# disqusShortname = "david"

paginate=10 # articles per page

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/davidxbors"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/visitorish/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4
